version: '3.8'
services:
  authentication:
    build:
      context: src/service/authentication/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on: 
      - authentication-db
  authentication-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
    ports:
      - "7001:5432"
  dashboard:
    build:
      context: src/service/dashboard/
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on: 
      - authentication-db
  dashboard-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
    ports:
      - "7002:5432"